"""Add country column to bank table

Revision ID: 1c6ae4a220fd
Revises: 48f1e6d2ba41
Create Date: 2025-11-20 23:53:30.610983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c6ae4a220fd'
down_revision: Union[str, None] = '48f1e6d2ba41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bank",
        sa.Column(
            "country", sa.String(length=50), nullable=False, server_default="Sri Lanka"
        ),
    )
    op.execute("UPDATE bank SET country = 'Sri Lanka' WHERE country IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank', 'country')
    # ### end Alembic commands ###
