"""Make the last_updated column nullable in raw_exchange_rates table

Revision ID: 352c4ac3436a
Revises: a36ef7a0f06e
Create Date: 2025-11-27 14:13:25.031472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '352c4ac3436a'
down_revision: Union[str, None] = 'a36ef7a0f06e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_exchange_rates', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_exchange_rates', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
