"""Add bank table

Revision ID: 48f1e6d2ba41
Revises: 79923375a858
Create Date: 2025-11-20 21:51:27.475425

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "48f1e6d2ba41"
down_revision: Union[str, None] = "79923375a858"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("rates_url", sa.String(length=255), nullable=False),
        sa.Column("logo_url", sa.String(length=255), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("scraper_type", sa.String(length=20), nullable=False),
        sa.Column("created_date", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(
        """
        INSERT INTO bank (code, name, rates_url, logo_url, active, scraper_type, created_date)
        VALUES
            ('commercial', 'Commercial Bank', 'https://www.combank.lk/rates-tariff#exchange-rates', 'https://cdn.brandfetch.io/idRazBOy4j/theme/dark/logo.svg?c=1bxid64Mup7aczewSAYMX&t=1763405600684', TRUE, 'html', NOW()),
            ('sampath', 'Sampath Bank', 'https://www.sampath.lk/api/exchange-rates', 'https://cdn.brandfetch.io/idWS-jlPHh/w/262/h/95/theme/dark/logo.png?c=1bxid64Mup7aczewSAYMX&t=1756394213832', TRUE, 'html', NOW()),
            ('nsb', 'National Savings Bank', 'https://www.nsb.lk/rates-tarriffs/nsb-exchange-rates/', NULL, TRUE, 'html', NOW()),
            ('boc', 'Bank of Ceylon', 'https://www.boc.lk/rates-tariff', 'https://cdn.brandfetch.io/idEvar2RB_/theme/dark/logo.svg?c=1bxid64Mup7aczewSAYMX&t=1668080646231', TRUE, 'html', NOW()),
            ('ntb', 'Nations Trust Bank', 'https://www.nationstrust.com/foreign-exchange-rates', NULL, TRUE, 'html', NOW()),
            ('hnb', 'HNB Bank', 'https://venus.hnb.lk/api/get_exchange_rates_contents_web', NULL, TRUE, 'api', NOW()),
            ('peoples', 'Peoples Bank', 'https://www.peoplesbank.lk/exchange-rates/', NULL, TRUE, 'html', NOW()),
            ('seylan', 'Seylan Bank', 'https://www.seylan.lk/exchange-rates', NULL, TRUE, 'html', NOW()),
            ('dfcc', 'DFCC Bank', 'https://www.dfcc.lk/rates-and-tariff/exchange-rates', NULL, TRUE, 'html', NOW())
        """
    )
    op.create_index(op.f("ix_bank_code"), "bank", ["code"], unique=True)
    op.create_index(
        op.f("ix_bank_created_date"), "bank", ["created_date"], unique=False
    )
    op.alter_column(
        "raw_exchange_rates", "tag", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.create_index(
        op.f("ix_raw_exchange_rates_created_date"),
        "raw_exchange_rates",
        ["created_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_exchange_rates_currency_code"),
        "raw_exchange_rates",
        ["currency_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_exchange_rates_tag"), "raw_exchange_rates", ["tag"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_raw_exchange_rates_tag"), table_name="raw_exchange_rates")
    op.drop_index(
        op.f("ix_raw_exchange_rates_currency_code"), table_name="raw_exchange_rates"
    )
    op.drop_index(
        op.f("ix_raw_exchange_rates_created_date"), table_name="raw_exchange_rates"
    )
    op.alter_column(
        "raw_exchange_rates", "tag", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.drop_index(op.f("ix_bank_created_date"), table_name="bank")
    op.drop_index(op.f("ix_bank_code"), table_name="bank")
    op.drop_table("bank")
    # ### end Alembic commands ###
