"""Initial schema

Revision ID: 79923375a858
Revises: 
Create Date: 2025-11-11 10:05:55.203673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79923375a858'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('last_updated', sa.TIMESTAMP(), nullable=False),
    sa.Column('source_url', sa.String(length=255), nullable=True),
    sa.Column('currency_name', sa.String(length=50), nullable=False),
    sa.Column('currency_code', sa.String(length=10), nullable=False),
    sa.Column('tt_buying', sa.Float(), nullable=True),
    sa.Column('tt_selling', sa.Float(), nullable=True),
    sa.Column('draft_buying', sa.Float(), nullable=True),
    sa.Column('draft_selling', sa.Float(), nullable=True),
    sa.Column('cheques_buying', sa.Float(), nullable=True),
    sa.Column('cheques_selling', sa.Float(), nullable=True),
    sa.Column('currency_buying', sa.Float(), nullable=True),
    sa.Column('currency_selling', sa.Float(), nullable=True),
    sa.Column('other_buying', sa.Float(), nullable=True),
    sa.Column('other_selling', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tag', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraper_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('finished_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correlation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraper_jobs')
    op.drop_table('raw_exchange_rates')
    # ### end Alembic commands ###
