"""index the columns in raw_exchange_rates table

Revision ID: a36ef7a0f06e
Revises: b8897a62cf91
Create Date: 2025-11-25 13:54:46.715037

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a36ef7a0f06e'
down_revision: Union[str, None] = 'b8897a62cf91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_raw_exchange_rates_bank_name'), 'raw_exchange_rates', ['bank_name'], unique=False)
    op.create_index(op.f('ix_raw_exchange_rates_currency_name'), 'raw_exchange_rates', ['currency_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_exchange_rates_currency_name'), table_name='raw_exchange_rates')
    op.drop_index(op.f('ix_raw_exchange_rates_bank_name'), table_name='raw_exchange_rates')
    # ### end Alembic commands ###
