"""Add currency table

Revision ID: b8897a62cf91
Revises: 1c6ae4a220fd
Create Date: 2025-11-23 22:56:44.708736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8897a62cf91'
down_revision: Union[str, None] = '1c6ae4a220fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(
        """
        INSERT INTO currency (code, symbol, name, country, active, created_date)
        VALUES
          ('USD', '$', 'US Dollar', 'United States', TRUE, NOW()),
          ('EUR', '€', 'Euro', 'European Union', TRUE, NOW()),
          ('GBP', '£', 'British Pound', 'United Kingdom', TRUE, NOW()),
          ('JPY', '¥', 'Japanese Yen', 'Japan', TRUE, NOW()),
          ('SGD', 'S$', 'Singapore Dollar', 'Singapore', TRUE, NOW()),
          ('AUD', 'A$', 'Australian Dollar', 'Australia', TRUE, NOW()),
          ('CHF', 'Fr.', 'Swiss Franc', 'Switzerland', TRUE, NOW()),
          ('KWD', 'د.ك', 'Kuwaiti Dinar', 'Kuwait', TRUE, NOW()),
          ('OMR', 'ر.ع', 'Omani Rial', 'Oman', TRUE, NOW()),
          ('SAR', 'ر.س', 'Saudi Riyal', 'Saudi Arabia', TRUE, NOW()),
          ('AED', 'د.إ', 'UAE Dirham', 'United Arab Emirates', TRUE, NOW()),
          ('QAR', 'ر.ق', 'Qatari Riyal', 'Qatar', TRUE, NOW()),
          ('JOD', 'د.أ', 'Jordanian Dinar', 'Jordan', TRUE, NOW()),
          ('BHD', 'د.ب', 'Bahraini Dinar', 'Bahrain', TRUE, NOW()),
          ('INR', '₹', 'Indian Rupee', 'India', TRUE, NOW()),
          ('CAD', 'C$', 'Canadian Dollar', 'Canada', TRUE, NOW()),
          ('NZD', 'NZ$', 'New Zealand Dollar', 'New Zealand', TRUE, NOW()),
          ('ZAR', 'R', 'South African Rand', 'South Africa', TRUE, NOW()),
          ('DKK', 'kr', 'Danish Krone', 'Denmark', TRUE, NOW()),
          ('KRW', '₩', 'South Korean Won', 'South Korea', TRUE, NOW()),
          ('SEK', 'kr', 'Swedish Krona', 'Sweden', TRUE, NOW()),
          ('NOK', 'kr', 'Norwegian Krone', 'Norway', TRUE, NOW()),
          ('CNY', '¥', 'Chinese Yuan', 'China', TRUE, NOW()),
          ('MYR', 'RM', 'Malaysian Ringgit', 'Malaysia', TRUE, NOW()),
          ('HKD', 'HK$', 'Hong Kong Dollar', 'Hong Kong', TRUE, NOW()),
          ('THB', '฿', 'Thai Baht', 'Thailand', TRUE, NOW())
        """
    )
    op.create_index(op.f('ix_currency_code'), 'currency', ['code'], unique=True)
    op.create_index(op.f('ix_currency_created_date'), 'currency', ['created_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_created_date'), table_name='currency')
    op.drop_index(op.f('ix_currency_code'), table_name='currency')
    op.drop_table('currency')
    # ### end Alembic commands ###
